### Simple signals analysis using:

* Z-Score
* SMA

Assumptions:

* We enter a long position if the close price is above the 20-day Simple Moving Average (SMA)
* We close the position when the close price goes below the 20-day SMA
* Short selling is not allowed
* The strategy is unit agnostic (we can enter a position of 1 share or 1000 shares) because we only care about the percentage change in the prices.

In [3]:
import os
import numpy as np
import pandas as pd
import datetime as dt
import yfinance as yf
import matplotlib.pyplot as plt
from scipy.stats import norm

In [6]:
from qf.core.data import DATA_DIR

ImportError: cannot import name 'DATA_DIR' from 'qf.core.data' (/Users/yevgeniy/Development/Projects/FinancialEngineering/quant-finance/qf/core/data.py)

In [2]:
prices_file = os.path.join(DATA_DIR, 'prices.csv')
prices_df = pd.read_csv(prices_file, parse_dates=['date'], index_col='date')
display(prices_df)

NameError: name 'DATA_DIR' is not defined

In [11]:
f"Available tickers: {list(prices_df.ticker.unique())}"

"Available tickers: ['AAPL', 'MSFT', 'AMZN', 'GOOG', 'FB', 'WMT', 'JPM', 'TSLA', 'NFLX', 'ADBE']"

### SMA signal for a single ticker

In [14]:
ticker = 'AAPL'

In [38]:
df = prices_df.loc[prices_df.ticker == ticker][['ticker', 'close']]

In [39]:
df['log_return'] = np.log(1 + df.close.shift(1))
df.dropna()

           ticker       close  log_return
date
2020-10-28   AAPL  110.842850    4.764100
2020-10-29   AAPL  114.949615    4.717095
2020-10-30   AAPL  108.510361    4.753156
2020-11-02   AAPL  108.420654    4.696019
2020-11-03   AAPL  110.085289    4.695200
...           ...         ...         ...
2021-04-20   AAPL  133.110001    4.911478
2021-04-21   AAPL  133.500000    4.898660
2021-04-22   AAPL  131.940002    4.901564
2021-04-23   AAPL  134.320007    4.889898
2021-04-26   AAPL  134.720001    4.907642

[123 rows x 3 columns]

In [40]:
display(df)

           ticker       close  log_return
date
2020-10-27   AAPL  116.225510         NaN
2020-10-28   AAPL  110.842850    4.764100
2020-10-29   AAPL  114.949615    4.717095
2020-10-30   AAPL  108.510361    4.753156
2020-11-02   AAPL  108.420654    4.696019
...           ...         ...         ...
2021-04-20   AAPL  133.110001    4.911478
2021-04-21   AAPL  133.500000    4.898660
2021-04-22   AAPL  131.940002    4.901564
2021-04-23   AAPL  134.320007    4.889898
2021-04-26   AAPL  134.720001    4.907642

[124 rows x 3 columns]